// Phase 5B — Generates supabase/seed.sql from static JSON data.
// Usage: npm run supabase:generate-seed
// Output is a standalone SQL file — safe to re-run (upserts only).

import { writeFileSync, readFileSync } from 'fs'
import { join } from 'path'

const ROOT = join(import.meta.dirname, '../..')
const SEED_PATH = join(ROOT, 'supabase/seed.sql')

function escape(s: string | null | undefined): string {
  if (s == null) return 'null'
  return `'${s.replace(/'/g, "''")}'`
}

function bool(b: boolean): string {
  return b ? 'true' : 'false'
}

function loadJson<T>(rel: string): T {
  return JSON.parse(readFileSync(join(ROOT, rel), 'utf8')) as T
}

interface Company {
  ticker: string
  name: string
  legalName?: string
  sector?: string
  industry?: string
  exchange?: string
  currency?: string
  country: string
  active: boolean
}

interface MacroIndicator {
  id: string
  region: string
  name: string
  shortName?: string
  category?: string
  unit?: string
  source?: string
}

const companies = loadJson<Company[]>('src/data/companies.json')
const macro = loadJson<MacroIndicator[]>('src/data/macroIndicators.json')

const lines: string[] = [
  '-- Phase 5B seed: static MVP reference data only.',
  `-- Generated by scripts/supabase/generateSeed.ts on ${new Date().toISOString().slice(0, 10)}`,
  '-- All records tagged static_mvp in metadata.',
  '-- Run: psql $SUPABASE_DATABASE_URL -f supabase/seed.sql',
  '',
  '-- ─── data_sources ──────────────────────────────────────────────────────────',
  "insert into data_sources (provider, source_type, display_name, base_url, status, metadata)",
  "values",
  "  ('static', 'static', 'Static MVP Data', null, 'active', '{\"static_mvp\": true}'),",
  "  ('bcch', 'api', 'Banco Central de Chile BDE', 'https://si3.bcentral.cl/SieteRestWS/SieteRestWS.ashx', 'inactive', '{\"static_mvp\": true}'),",
  "  ('cmf', 'scrape', 'CMF Chile', 'https://www.cmfchile.cl', 'inactive', '{\"static_mvp\": true}'),",
  "  ('brain_data', 'api', 'Brain Data / Bolsa de Santiago', null, 'inactive', '{\"static_mvp\": true}')",
  "on conflict do nothing;",
  '',
  '-- ─── companies ─────────────────────────────────────────────────────────────',
  'insert into companies (ticker, name, legal_name, sector, industry, exchange, currency, country, active, metadata)',
  'values',
]

companies.forEach((c, i) => {
  const last = i === companies.length - 1
  lines.push(
    `  (${escape(c.ticker)}, ${escape(c.name)}, ${escape(c.legalName)}, ` +
    `${escape(c.sector)}, ${escape(c.industry)}, ${escape(c.exchange)}, ` +
    `${escape(c.currency)}, ${escape(c.country)}, ${bool(c.active)}, '{"static_mvp": true}')${last ? '' : ','}`
  )
})

lines.push(
  'on conflict (ticker) do update set',
  '  name = excluded.name,',
  '  legal_name = excluded.legal_name,',
  '  sector = excluded.sector,',
  '  industry = excluded.industry,',
  '  updated_at = now();',
  '',
  '-- ─── macro_indicators ───────────────────────────────────────────────────────',
  'insert into macro_indicators (id, region, name, short_name, category, unit, source_provider, live_enabled, metadata)',
  'values',
)

macro.forEach((m, i) => {
  const last = i === macro.length - 1
  const provider = m.source?.toLowerCase().includes('bcch') || m.source?.toLowerCase().includes('banco central')
    ? 'bcch'
    : m.source?.toLowerCase().includes('cmf')
    ? 'cmf'
    : 'static'
  lines.push(
    `  (${escape(m.id)}, ${escape(m.region)}, ${escape(m.name)}, ` +
    `${escape(m.shortName)}, ${escape(m.category)}, ${escape(m.unit)}, ` +
    `${escape(provider)}, false, '{"static_mvp": true}')${last ? '' : ','}`
  )
})

lines.push(
  'on conflict (id) do update set',
  '  name = excluded.name,',
  '  short_name = excluded.short_name,',
  '  category = excluded.category,',
  '  unit = excluded.unit,',
  '  updated_at = now();',
)

writeFileSync(SEED_PATH, lines.join('\n') + '\n', 'utf8')
console.log(`[supabase:generate-seed] Written ${SEED_PATH}`)
